### PR TITLE
HOWTOs - General, ReferenceFeed and EventPostProcessing

### PR DESCRIPTION
**Pull request by DS177**
HOWTO Document Tranche2B
New HOWTOs for General, ReferenceFeed and EventPostProcessing
Tweak some exisiting HOWTOs:
Apache HTTPD datasource remediated -timezone/referrer URL and changed eventdetail xslt, 
GeoHost datasource - add additional hosts and change some ip addressing
Redo multiple screenshots due to data source tweaks

### CODE REVIEW

**Comment by DS177** [comment]
@burnalting @stroomdev66 @at055612 
Hi, can I get a review of this documentation please.
Is this the only way I can add reviewers - via the comment process?. Do you prefer notification to come this way or via Slack?

**Comment by burnalting** [comment]
This medium works for me. Will review and comment in the next day or so, unless others beat me to it. Formal acceptance will need to be by @stroomdev66 or @at055612  though.

**Comment by burnalting** [comment]
All, a quick review offers based on reviewing https://github.com/DS177/stroom-docs/tree/docs-tranche2B.

I have grouped issues based on the .md file where spelling/punctuation has an
  existing extract 'Should be' corrected extract



HOWTOs/StroomHowTos.md:
ow to extract xertain events from the Stroom    Should be               ow to extract certain events from the Stroom

Under Event Feed Processing, if I on "Apache HTTPD Event Feed" (aka https://github.com/DS177/stroom-docs/blob/docs-tranche2B/HOWTOs/HOWTOs/EventFeeds/CreateApacheHTTPDEventFeed.md) I get a 404 error


EventPostProcessing/EventForwardingHowTo.md:
name this xsltFilter ClientGBRxsltFilter.       Should be               Name this xsltFilter ClientGBRxsltFilter.
e pane. the first Event in the                  Should be               e pane. The first Event in the

ReferenceFeeds/CreateSimpleReferenceFeed.md:

When the Choose item selection window appears, navigate to Template Pipelines system group (if not already displayed), and select (left click) the Pipeline Reference Data pipeline

May want to cite https://github.com/gchq/stroom-content/blob/master/source/template-pipelines/README.md as a source for Template Pipelines

We now need to create our translation. This XSLT translation will convert simple records XML data into ReferenceData records - see the Stroom reference-data v2.0.1 Schema for details.

May want to cite https://github.com/gchq/stroom-content/blob/master/source/core-xml-schemas/README.md as a source.

ReferenceFeeds/UseSimpleReferenceFeedHowTo.md:

....
lookup(String map, String key, String time, Boolean ignoreWarnings) Look up a reference data map using a specified time, e.g. the event time, and ignore any warnings generated by a failed lookup

May want to add all current options. Extracting from user-guide/pipelines/xslt/xslt-functions.md
lookup(String map, String key) - Look up a reference data map using the period start time
lookup(String map, String key, String time) - Look up a reference data map using a specified time, e.g. the event time
lookup(String map, String key, String time, Boolean ignoreWarnings) - Look up a reference data map using a specified time, e.g. the event time, and ignore any warnings generated by a failed lookup
lookup(String map, String key, String time, Boolean ignoreWarnings, Boolean trace) - Look up a reference data map using a specified time, e.g. the event time, ignore any warnings generated by a failed lookup and get trace information for the path taken to resolve the lookup.


General/EnablingProcessorsHowTo.md:

NOTE: If you need to reprocess bulk streams you need to be aware that there is an upper limit of 1000 streams that can be reprocessed in a single batch. As at Stroom v6 if you exceed this number then you receive no error notification but the task never completes. The reason for this behaviour is to do with database performance and complexity. When you reprocess the current selection of filtered data, it can contain data that has resulted from many pipelines and this requires creation of new processor filters for each of these pipelines. Due to this complexity there exists an arbitrary limit of 1000 streams.

Offer a solution of selecting a limited set of 'Events' based on filtering on event stream timestampt to ensure you are less than 1000 and then perform a 'rinse and repeat' activity of submitting a 'batch' of streams to reprocess to get all streams in the greater than 1000 list.
In a worst case senario, one can also delete a set of streams for a given time period and then reprocess them all. The only risk here is that if there
are other pipelines that trigger on Event creation, you will activate them. That is you may have two index entries in an index, although Stroom dashboa
rds silently caters for this or you may re-flatten data to some exteral downstream capability.
~

**Comment by DS177** [comment]
@burnalting - Hi Burn have implemented your feedback. Can you cast your eye over it before I request formal acceptance.
Thanks

**Comment by DS177** [comment]
@burnalting 
Hi I have incorporated Burns latest comments. 
Think this batch is now ready for formal acceptance - @stroomdev66 @at055612

**Comment by at055612** [comment]
A couple of initial comments.

There seem to be a lot of duplicated png files in HOWTOS/resources and HOWTOS/resources/v6.  Also the ones in resources are marked executable for some reason.

For the document properties bit at the top of your pages.  This is a good idea but not sure we need the author on there.  Git can tell us the history of each .md file.  The date is useful as is the version of stroom.  How about 
```> * Version Information: Created with Stroom v6.x  
* Last Updated: 8 May 2020  
* See also: [HOWTO - Creating a Simple Reference Feed](../ReferenceFeeds/CreateSimpleReferenceFeed.md)
```

Note the [space][space] at the end of lines to force markdown to continue the quote block.  Markdown is a bit of a mess.  The above renders differently in gitbook as it does in grip.

image

For info, if you want to view the generated html then you can install gitbook and run the following in the root of the repo.
```
gitbook install
gitbook serve
```
That will then run up a little web server on 4000 serving the pages and updating them when you save files.

Some of the pages are pretty huge.  It may be worth splitting them into multiple sub docs or having a table of contents at the top.

**Comment by DS177** [comment]
@at055612 - Thanks for the feedback.
Regarding the *.png files I don't think there are duplications in these directories (or I'm not on the same page as you about the issue). The rationale behind creating the /resources/v6 directory was discussed in PR  https://github.com/gchq/stroom-docs/pull/36

The png's in /resources were created by @burnalting on versions up to and including v5. The ones in /resources/v6 have been created in v6 as part of this pack of work I'm doing. Envision anything created on v7 will live in a directory /resources/v7. This way we can more easily keep a handle on what is getting dated and needs a refresh. Or if documentation ever gets split out to a per version level we are ahead of the game. If this approach has issues fine to have further discussion.
Re document properties -happy to remove authorship. Like your "See also" with links suggestion. Will adopt and recomit.
Thanks for the tip on gitbook - have been taking the fingers-crossed approach on that front which isn't a great strategy. Will be much better being able to see the finished view before comit. Will install and have a play. Not a fan of [space][space] but if it is what works best for the final product presentation I'll adapt.

**Comment by DS177** [comment]
@at055612 
Have made the changes you suggested back in May 2020. Can you please review and accept

**Pull request merged**
